apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-lego
  namespace: ingress
data:
  # modify this to specify your address
  lego.email: "daniel.bodnar@perspectives.org"
  # use letencrypt's production api
  lego.url: "https://acme-v01.api.letsencrypt.org/directory"
