tags:
  db: false
  platform: true
  platformdb: true
  monitoring: true
ingress:
  ui:
    enabled: true
    annotations: {}
    path: /
    hosts:
    - containerum.psplabs.org
    tls: []
  api:
    enabled: true
    annotations: {}
    path: /
    hosts:
    - api.containerum.psplabs.org
    tls: []
ui:
  env:
    local:
      COUNTRY: US
      API_PROTOCOL_TYPE: no-ssl
      API_PORT: null
      LATEST_RELEASE: 1.2.1
    global:
      API_HOST: api.containerum.psplabs.org
      RECAPTCHA: null
mail:
  persistence:
    enabled: false
  env:
    local:
      CH_MAIL_USER_MANAGER_URL: null
      CH_MAIL_SMTP_PASSWORD: null
    global:
      CH_MAIL_SMTP_ADDR: null
      CH_MAIL_SMTP_LOGIN: null
      CH_MAIL_SENDER_MAIL_SIMPLE: null
      CH_MAIL_SENDER_MAIL: null
auth:
  persistence:
    enabled: false
user-manager:
  tags:
    platformdb: true
  env:
    global:
      CH_USER_PG_DBNAME: containerum
      CH_USER_PG_LOGIN: postgres
    local:
      CH_USER_PG_ADDR: null
      CH_USER_MAIL_URL: null
      CH_USER_AUTH_GRPC_ADDR: null
      CH_USER_AUTH_HTTP_ADDR: null
      CH_USER_PERMISSIONS_URL: null
      CH_USER_ADMIN_PASSWORD: pspnwa2018
solutions:
  tags:
    platformdb: true
  env:
    global:
      CH_SOLUTIONS_PG_DBNAME: containerum
      CH_SOLUTIONS_PG_LOGIN: postgres
    local:
      CH_SOLUTIONS_PG_ADDR: null
      CH_SOLUTIONS_PG_PASSWORD: null
      CH_SOLUTIONS_RESOURCE_URL: null
      CH_SOLUTIONS_KUBE_API_URL: null
permissions:
  tags:
    platformdb: true
  env:
    global:
      DB_BASE: containerum
      DB_USER: postgres
    local:
      DB_HOST: null
      AUTH_ADDR: null
      USER_ADDR: null
      KUBE_API_ADDR: null
      RESOURCE_SERVICE_ADDR: null
      BILLING_ADDR: null
      SOLUTIONS_ADDR: null
      VOLUME_MANAGER_ADDR: null
resource:
  tags:
    platformdb: true
  env:
    global:
      CH_RESOURCE_MONGO_DB: containerum
      CH_RESOURCE_MONGO_LOGIN: mongo
      CH_RESOURCE_MIN_SERVICE_PORT: 30000
      CH_RESOURCE_MAX_SERVICE_PORT: 32767
    local:
      CH_RESOURCE_MONGO_ADDR: null
      CH_RESOURCE_KUBE_API_ADDR: null
      CH_RESOURCE_PERMISSIONS_ADDR: null
nodemetrics:
  env:
    local:
      PROMETHEUS_ADDR: null
volume:
  tags:
    platformdb: true
  env:
    global:
      DB_BASE: containerum
      DB_USER: postgres
    local:
      DB_HOST: null
      KUBE_API_ADDR: null
      BILLING_ADDR: null
api-gateway:
  env:
    local:
      SERVICE_HOST_PREFIX: release-name
      GRPC_AUTH_ADDRESS: null
auth:
  persistence:
    enabled: false
kube-importer:
  rbac:
    serviceAccountName: release-name
  env:
    global:
      CH_KUBE_IMPORTER_EXCLUDED_NS: default,kube-system
    local:
      CH_KUBE_IMPORTER_RESOURCE_URL: null
      CH_KUBE_IMPORTER_PERMISSIONS_URL: null
      CH_KUBE_IMPORTER_VOLUMES_URL: null
postgresql:
  persistence:
    enabled: false
  postgresDatabase: containerum
mongodb:
  persistence:
    enabled: false
  mongodbDatabase: containerum
  mongodbUsername: mongo
