apiVersion: kubeadm.k8s.io/v1alpha2
kind: MasterConfiguration
api:
  advertiseAddress: ${api_advertise_addresses}
etcd:
  external:
    endpoints:
    ${etcd_endpoints}
apiServerCertSANs:
  ${cert_sans}
kubeletConfiguration:
  baseConfig:
    failSwapOn: false
