apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: default
spec:
  acme:
    email: daniel.bodnar@perspectives.org
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    dns01:
      providers:
      - name: cloudflare-dns
        cloudflare:
          email: daniel.bodnar@perspectives.org
          apiKeySecretRef:
            name: cert-manager-secrets
            key: CLOUDFLARE_TOKEN
