apiVersion: v1
kind: Service
metadata:
  labels:
    app: echo
  name: echo
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app: echo
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: echo
  name: echo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: echo
        image: gcr.io/hello-minikube-zero-install/hello-node
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 20Mi
      terminationGracePeriodSeconds: 60
---
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   annotations:
#     kubernetes.io/ingress.class: argo-tunnel
#     argo.cloudflare.com/lb-pool: prod-pool
#   labels:
#     ingress: argo-tunnel
#   name: argo-tunnel
# spec:
#   rules:
#   - host: echo-service.pspusa.app
#     http:
#       paths:
#       - backend:
#           serviceName: echo
#           servicePort: https
# ---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: auth-test-app.psplabs.org
    external-dns.alpha.kubernetes.io/ttl: "120" #optional
    ingress.kubernetes.io/oauth: oauth2_proxy
  name: auth-test-app
spec:
  rules:
  - host: auth-test-app.psplabs.org
    http:
      paths:
      - backend:
          serviceName: oauth2-proxy
          servicePort: 4180
        path: /oauth2
      - backend:
          serviceName: echoserver
          servicePort: 8080
        path: /
